version: '3'

tasks:
  gen:
    desc: "11ty build"
    cmds:
      - npx @11ty/eleventy

  clean:
    desc: "11ty clean"
    cmds:
      - rm -r _site

  serve:
    desc: "11ty serve"
    cmds:
      - npx @11ty/eleventy --serve

  deploy:
    desc: "Deploy to Cloudflare pages"
    cmds:
      - task clean gen
      - npx wrangler deploy

  logs:sync:
    desc: "rclone sync logs"
    cmds:
      - rclone sync iamjonas-r2:iamjonas-access-logs/logs ./logs  --progress

  logs:process:
    desc: "Process logs"
    dir: ./logs
    cmds:
      - goaccess -p ../.goaccessrc *
